export const dashboardStyles = {
  page: {
    minHeight: "100vh",
    background: "radial-gradient(ellipse at top, #f8fafc, #f1f5f9)",
    padding: 24,
    fontFamily: "Inter, var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
    color: "#0f172a",
  } as const,
  loginContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 0",
    minHeight: "100vh",
  } as const,
  loginCard: {
    width: "100%",
    maxWidth: 420,
    background: "#ffffff",
    borderRadius: 20,
    padding: "48px 40px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05), 0 20px 50px rgba(15, 23, 42, 0.06)",
    border: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 24,
  } as const,
  loginHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
    textAlign: "center",
  } as const,
  loginForm: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
    marginBottom: 0,
  } as const,
  errorMessage: {
    padding: "10px 12px",
    borderRadius: 8,
    background: "rgba(239, 68, 68, 0.08)",
    color: "#dc2626",
    fontSize: 13,
    fontWeight: 600,
    border: "1px solid rgba(239, 68, 68, 0.12)",
  } as const,
  shell: {
    maxWidth: 1400,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: 24,
  } as const,
  navbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "18px 24px",
    background: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    borderRadius: 16,
    boxShadow: "0 20px 40px rgba(15, 23, 42, 0.08)",
    color: "white",
    flexWrap: "wrap",
    gap: 12,
    border: "1px solid rgba(255, 255, 255, 0.08)",
  } as const,
  brandWrap: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  } as const,
  brandMark: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)",
    fontWeight: 800,
    fontSize: 20,
    color: "white",
    boxShadow: "0 8px 16px rgba(37, 99, 235, 0.25)",
  } as const,
  brand: {
    fontSize: 24,
    fontWeight: 800,
    letterSpacing: -0.5,
  } as const,
  subtitle: {
    fontSize: 12,
    opacity: 0.75,
    marginTop: 2,
  } as const,
  navActions: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  } as const,
  propertyPill: {
    padding: "6px 12px",
    borderRadius: 999,
    background: "rgba(255, 255, 255, 0.1)",
    fontSize: 13,
    border: "1px solid rgba(255, 255, 255, 0.15)",
    fontWeight: 600,
  } as const,
  select: {
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid rgba(255, 255, 255, 0.15)",
    background: "rgba(255, 255, 255, 0.05)",
    color: "white",
    outline: "none",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
  } as const,
  userInfo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 2,
  } as const,
  userName: {
    fontWeight: 700,
    fontSize: 14,
    color: "white",
  } as const,
  userRole: {
    fontSize: 12,
    opacity: 0.8,
    color: "white",
  } as const,
  userDetails: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    opacity: 0.88,
    color: "white",
  } as const,
  userSeparator: {
    opacity: 0.6,
  } as const,
  userSubRole: {
    fontStyle: "italic",
  } as const,
  logoutButton: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid rgba(239, 68, 68, 0.3)",
    background: "rgba(239, 68, 68, 0.15)",
    color: "#f87171",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 13,
  } as const,
  loading: {
    padding: "12px 16px",
    borderRadius: 12,
    background: "#ffffff",
    color: "#2563eb",
    fontWeight: 600,
    boxShadow: "0 4px 12px rgba(15, 23, 42, 0.04)",
    border: "1px solid #e2e8f0",
  } as const,
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 16,
  } as const,
  metricCard: {
    background: "#ffffff",
    borderRadius: 12,
    padding: 20,
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05), 0 4px 20px rgba(15, 23, 42, 0.01)",
    border: "1px solid #e2e8f0",
  } as const,
  metricIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    fontWeight: 800,
  } as const,
  metricValue: {
    fontSize: 24,
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1.1,
  } as const,
  metricValueWrap: {
    wordBreak: "break-word",
    overflowWrap: "anywhere",
    whiteSpace: "normal",
    maxWidth: "100%",
  } as const,
  metricHint: {
    marginTop: 6,
    color: "#64748b",
    fontSize: 12,
  } as const,
  gridTwo: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 20,
  } as const,
  gridSingle: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 20,
  } as const,
  card: {
    background: "#ffffff",
    borderRadius: 16,
    padding: 24,
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.05), 0 10px 40px rgba(15, 23, 42, 0.03)",
    border: "1px solid #e2e8f0",
  } as const,
  glassCard: {
    background: "#ffffff",
  } as const,
  cardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 8,
  } as const,
  cardTitle: {
    margin: 0,
    fontSize: 18,
    fontWeight: 700,
    color: "#0f172a",
    letterSpacing: "-0.2px",
  } as const,
  cardSubtitle: {
    margin: "4px 0 0",
    color: "#64748b",
    fontSize: 13,
  } as const,
  liveBadge: {
    padding: "4px 8px",
    borderRadius: 999,
    background: "rgba(16, 185, 129, 0.1)",
    color: "#10b981",
    fontSize: 11,
    fontWeight: 700,
    border: "1px solid rgba(16, 185, 129, 0.15)",
  } as const,
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 16,
    alignItems: "end",
  } as const,
  fieldBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } as const,
  fieldLabel: {
    fontSize: 11,
    color: "#475569",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  } as const,
  input: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    outline: "none",
    fontSize: 14,
    color: "#0f172a",
  } as const,
  primaryButton: {
    padding: "10px 16px",
    borderRadius: 8,
    border: "none",
    background: "linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)",
    color: "white",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
    boxShadow: "0 4px 12px rgba(37, 99, 235, 0.2)",
  } as const,
  secondaryButton: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    background: "#ffffff",
    color: "#334155",
    cursor: "pointer",
    fontWeight: 500,
    fontSize: 13,
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.05)",
  } as const,
  widgetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: 12,
    marginBottom: 12,
  } as const,
  reconciliationGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: 12,
    marginBottom: 12,
  } as const,
  reconciliationCard: {
    padding: 16,
    borderRadius: 10,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  } as const,
  reconciliationLabel: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  } as const,
  reconciliationValue: {
    fontSize: 18,
    fontWeight: 800,
    color: "#0f172a",
  } as const,
  commentBox: {
    padding: 16,
    borderRadius: 10,
    background: "linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)",
    border: "1px solid #e2e8f0",
    marginBottom: 12,
  } as const,
  commentTitle: {
    color: "#0f172a",
    fontWeight: 700,
    fontSize: 13,
    marginBottom: 4,
  } as const,
  commentText: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 1.5,
  } as const,
  widgetCard: {
    padding: 16,
    borderRadius: 10,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  } as const,
  widgetLabel: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  } as const,
  widgetValue: {
    fontSize: 20,
    fontWeight: 800,
    color: "#0f172a",
  } as const,
  requestRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    padding: "16px 0",
    borderTop: "1px solid #e2e8f0",
    marginTop: 8,
  } as const,
  requestActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } as const,
  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "4px 8px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "capitalize",
  } as const,
  metaText: {
    color: "#64748b",
    fontSize: 13,
    marginTop: 2,
  } as const,
  emptyState: {
    padding: 24,
    borderRadius: 10,
    background: "#f8fafc",
    color: "#64748b",
    textAlign: "center",
    marginTop: 10,
    border: "1px dashed #cbd5e1",
    fontSize: 13,
  } as const,
  tableWrap: {
    overflowX: "auto",
  } as const,
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 14,
  } as const,
  th: {
    textAlign: "left",
    padding: "12px 14px",
    color: "#475569",
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    borderBottom: "1px solid #e2e8f0",
    position: "sticky",
    top: 0,
    background: "#ffffff",
    zIndex: 1,
  } as const,
  trRow: {
    background: "#ffffff",
  } as const,
  td: {
    padding: "12px 14px",
    borderBottom: "1px solid #f1f5f9",
    color: "#334155",
  } as const,
  consoleCard: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderRadius: 10,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    marginTop: 10,
  } as const,
  timeline: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } as const,
  timelineItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderRadius: 10,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
  } as const,
  timelineIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    fontWeight: 800,
  } as const,
  timelineTitle: {
    fontWeight: 600,
    color: "#0f172a",
    fontSize: 14,
  } as const,
  timelineStamp: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: 600,
  } as const,
} as const;
