export const dashboardStyles = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(180deg, #f8fafc 0%, #eef4ff 100%)",
    padding: 24,
    fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    color: "#0f172a",
  } as const,
  loginContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 0",
    minHeight: "100vh",
  } as const,
  loginCard: {
    width: "100%",
    maxWidth: 440,
    background: "rgba(255,255,255,0.96)",
    borderRadius: 24,
    padding: "44px 40px 40px",
    boxShadow: "0 20px 60px rgba(15, 23, 42, 0.15)",
    border: "1px solid rgba(226, 232, 240, 0.85)",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 24,
  } as const,
  loginHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
    textAlign: "center",
  } as const,
  loginForm: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    marginBottom: 0,
  } as const,
  errorMessage: {
    padding: 10,
    borderRadius: 10,
    background: "rgba(239, 68, 68, 0.12)",
    color: "#dc2626",
    fontSize: 13,
    fontWeight: 600,
  } as const,
  shell: {
    maxWidth: 1400,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: 20,
  } as const,
  navbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "22px 26px",
    background: "linear-gradient(135deg, #1e3a8a 0%, #2563eb 100%)",
    borderRadius: 24,
    boxShadow: "0 18px 45px rgba(30, 58, 138, 0.22)",
    color: "white",
    flexWrap: "wrap",
    gap: 12,
  } as const,
  brandWrap: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  } as const,
  brandMark: {
    width: 46,
    height: 46,
    borderRadius: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,0.2)",
    fontWeight: 800,
    fontSize: 22,
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.22)",
  } as const,
  brand: {
    fontSize: 28,
    fontWeight: 800,
    letterSpacing: -0.5,
  } as const,
  subtitle: {
    fontSize: 13,
    opacity: 0.92,
    marginTop: 4,
  } as const,
  navActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } as const,
  propertyPill: {
    padding: "8px 12px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.16)",
    fontSize: 14,
    border: "1px solid rgba(255,255,255,0.2)",
  } as const,
  select: {
    padding: "10px 12px",
    borderRadius: 12,
    border: "1px solid rgba(255,255,255,0.2)",
    background: "white",
    color: "#12355b",
    outline: "none",
  } as const,
  userInfo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 2,
  } as const,
  userName: {
    fontWeight: 700,
    fontSize: 14,
    color: "white",
  } as const,
  userRole: {
    fontSize: 12,
    opacity: 0.88,
    color: "white",
  } as const,
  userDetails: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    opacity: 0.88,
    color: "white",
  } as const,
  userSeparator: {
    opacity: 0.6,
  } as const,
  userSubRole: {
    fontStyle: "italic",
  } as const,
  logoutButton: {
    padding: "8px 14px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.2)",
    background: "rgba(255,255,255,0.1)",
    color: "white",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 13,
  } as const,
  loading: {
    padding: "12px 16px",
    borderRadius: 16,
    background: "rgba(255,255,255,0.9)",
    color: "#1e3a8a",
    fontWeight: 600,
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.06)",
  } as const,
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 16,
  } as const,
  metricCard: {
    background: "rgba(255,255,255,0.94)",
    borderRadius: 18,
    padding: 20,
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.06)",
    border: "1px solid rgba(226, 232, 240, 0.8)",
    backdropFilter: "blur(12px)",
  } as const,
  metricIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    fontWeight: 800,
  } as const,
  metricValue: {
    fontSize: 28,
    fontWeight: 800,
    color: "#12355b",
    lineHeight: 1.1,
  } as const,
  metricValueWrap: {
    wordBreak: "break-word",
    overflowWrap: "anywhere",
    whiteSpace: "normal",
    maxWidth: "100%",
  } as const,
  metricHint: {
    marginTop: 6,
    color: "#64748b",
    fontSize: 12,
  } as const,
  gridTwo: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: 20,
  } as const,
  gridSingle: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 20,
  } as const,
  card: {
    background: "rgba(255,255,255,0.94)",
    borderRadius: 22,
    padding: 20,
    boxShadow: "0 12px 32px rgba(15, 23, 42, 0.06)",
    border: "1px solid rgba(226, 232, 240, 0.85)",
  } as const,
  glassCard: {
    background: "linear-gradient(135deg, rgba(255,255,255,0.96) 0%, rgba(248,250,252,0.88) 100%)",
    backdropFilter: "blur(16px)",
  } as const,
  cardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 8,
  } as const,
  cardTitle: {
    margin: 0,
    fontSize: 20,
    color: "#12355b",
  } as const,
  cardSubtitle: {
    margin: "4px 0 0",
    color: "#64748b",
    fontSize: 13,
  } as const,
  liveBadge: {
    padding: "6px 10px",
    borderRadius: 999,
    background: "rgba(16, 185, 129, 0.14)",
    color: "#10b981",
    fontSize: 12,
    fontWeight: 700,
  } as const,
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 12,
    alignItems: "end",
  } as const,
  fieldBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } as const,
  fieldLabel: {
    fontSize: 12,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  } as const,
  input: {
    width: "100%",
    padding: "11px 12px",
    borderRadius: 12,
    border: "1px solid #dbe4f0",
    background: "#f8fafc",
    outline: "none",
    fontSize: 14,
    color: "#0f172a",
  } as const,
  primaryButton: {
    padding: "11px 14px",
    borderRadius: 12,
    border: "none",
    background: "linear-gradient(135deg, #1e3a8a 0%, #2563eb 100%)",
    color: "white",
    cursor: "pointer",
    fontWeight: 700,
    boxShadow: "0 10px 22px rgba(37, 99, 235, 0.22)",
  } as const,
  secondaryButton: {
    padding: "8px 12px",
    borderRadius: 10,
    border: "1px solid #dbe4f0",
    background: "white",
    color: "#12355b",
    cursor: "pointer",
    fontWeight: 600,
  } as const,
  widgetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: 10,
    marginBottom: 12,
  } as const,
  reconciliationGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: 10,
    marginBottom: 12,
  } as const,
  reconciliationCard: {
    padding: 12,
    borderRadius: 14,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  } as const,
  reconciliationLabel: {
    color: "#64748b",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 6,
  } as const,
  reconciliationValue: {
    fontSize: 20,
    fontWeight: 800,
    color: "#0f172a",
  } as const,
  commentBox: {
    padding: 12,
    borderRadius: 14,
    background: "linear-gradient(135deg, #eff6ff 0%, #f8fafc 100%)",
    border: "1px solid #dbeafe",
    marginBottom: 10,
  } as const,
  commentTitle: {
    color: "#1e3a8a",
    fontWeight: 700,
    fontSize: 13,
    marginBottom: 4,
  } as const,
  commentText: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 1.5,
  } as const,
  widgetCard: {
    padding: 12,
    borderRadius: 14,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  } as const,
  widgetLabel: {
    color: "#64748b",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 6,
  } as const,
  widgetValue: {
    fontSize: 22,
    fontWeight: 800,
    color: "#12355b",
  } as const,
  requestRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    padding: "12px 0",
    borderTop: "1px solid #e2e8f0",
    marginTop: 8,
  } as const,
  requestActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } as const,
  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "6px 10px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    textTransform: "capitalize",
  } as const,
  metaText: {
    color: "#64748b",
    fontSize: 13,
    marginTop: 2,
  } as const,
  emptyState: {
    padding: 16,
    borderRadius: 12,
    background: "#f8fafc",
    color: "#64748b",
    textAlign: "center",
    marginTop: 10,
  } as const,
  tableWrap: {
    overflowX: "auto",
  } as const,
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 14,
  } as const,
  th: {
    textAlign: "left",
    padding: "12px 10px",
    color: "#64748b",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    borderBottom: "1px solid #e2e8f0",
    position: "sticky",
    top: 0,
    background: "#ffffff",
    zIndex: 1,
  } as const,
  trRow: {
    background: "#ffffff",
  } as const,
  td: {
    padding: "12px 10px",
    borderBottom: "1px solid #f1f5f9",
  } as const,
  consoleCard: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
    borderRadius: 14,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    marginTop: 10,
  } as const,
  timeline: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } as const,
  timelineItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 14,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  } as const,
  timelineIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    fontWeight: 800,
  } as const,
  timelineTitle: {
    fontWeight: 700,
    color: "#12355b",
  } as const,
  timelineStamp: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: 600,
  } as const,
} as const;
